### ISSUE TITLE
My eyes are bleeding

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#192] opened 2021-12-16 07:27 UTC
![Screenshot_20211216-082204.jpg](https://user-images.githubusercontent.com/3205330/146326736-bbed7695-15a0-4769-ab38-8b371f65db2d.jpg)
Please help

**Comment by eric-taix** [comment] 2021-12-16 09:20
Sorry to blend your eyes 😜. Duplicate of #160

**Closed** 2021-12-16 09:59 UTC
Labels: duplicate

**Comment by matt-aubert** [comment] 2021-12-16 10:00
duplicate
